version: '3.8'

volumes:
  datafiles:

services:
  database:
    image: mysql
    volumes:
      - datafiles:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ame0372
      MYSQL_DATABASE: trade

  api:
    build:
      context: ./api_pi_pi_2
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "5184:8080"
    environment:
      - DBHOST=database
      - ASPNETCORE_ENVIRONMENT=Development
      - DefaultConnection=server=database;username=root;password=ame0372;database=trade

